name: build

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build --if-present
      # - run: npm test
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      - name: Copy to domain-graph/domain-graph.github.io
        uses: cpina/github-action-push-to-another-repository@v1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist'
          user-email: stephen.konves@gmail.com
          destination-github-username: 'skonves'
          destination-repository-username: 'domain-graph'
          destination-repository-name: 'domain-graph.github.io'
