name: build

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build --if-present
      # - run: npm test
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/
          retention-days: 1
  deploy-github:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Copy to domain-graph/domain-graph.github.io
        uses: cpina/github-action-push-to-another-repository@v1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'build/dist/'
          user-email: stephen.konves@gmail.com
          destination-github-username: 'skonves'
          destination-repository-username: 'domain-graph'
          destination-repository-name: 'domain-graph.github.io'
  deploy-netlify:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build/
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './build/dist'
          functions-dir: './build/functions'
          production-branch: netlify
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
